### ISSUE TITLE
Integration Stopped After 2021.6 update

### ISSUE THREAD

**Issue by akluthe** [pdugas/recteq#16]
Hey there,

This integration has been chugging away for a while and works great.

Today I updated Home assistant to 2021.6 and it looks like the integration stopped working.  It also stopped showing up in the integrations list to try and set it back up as I have done before.

Invalid config
The following integrations and platforms could not be set up:

recteq

Setup failed for recteq: Integration not found.

**Comment by akluthe** [comment]
It was the manifest that just needed updated! Got it working again per this post.

https://community.home-assistant.io/t/rec-tec-wifi-grill-control/205372/36

**Comment by pdugas** [comment]
Sorry I've been AWOL. New gig, jammed. Glad you figured it out.
