### ISSUE TITLE
Cannot Connect to RT700

### ISSUE THREAD

**Issue by eclipse1482** [pdugas/recteq#18]
First of all, thank you for creating this integration! I am using it primarily because my Recteq app notifications have been unreliable.. Makes it difficult to relax while my grill does the work!

I am having an issue connecting my grill to Home Assistant though. I went with the method to grab the 1.abj file and ctrl+f found the gwid, then the local key, then the IP address. My Recteq IP address seems to be something along the lines of 73.37.xxx.xxx. I saw somewhere in your write-up (I think for the option to search with tuyapower) that the IP address should be 10.0.xxx.xxx. Is that a hard rule? 

Anyways, I entered this information into the integration, but my grill has never been able to connect. I've tried this with Protocol 3.1 and 3.3. Am I doing something wrong? Is it possible I have the wrong IP address? Any other ideas?

**Comment by eclipse1482** [comment]
I solved the issue. The IP address listed on the 1.abj file does not work. I had to scan for my device with the python tuyapower command. I scanned once, unplugged my grill, scanned again, and then was able to identify what the correct device was. I entered this IP address and it works like a charm!

**Comment by pdugas** [comment]
Hi @mathys-lab. Glad you were able to make it work.  I was running mine today with a few port butts.  Yum!

**Comment by eclipse1482** [comment]
Pork butt is hard to beat! I did some brats and burgers today.

Really appreciate you pulling this integration together. Please reach out if there is anything you need help with such as testing or putting together documentation. I'd be happy to help if I can.
